function r=integrand_2_on_edges_z(x,y,sigma,edge_information,basis_type,eipsilon,e,beta)
%The integrand of the integral on the Dirichelet boundary edges
normal_vector=edge_information(1:2);
r=-((diffusive_coefficient_11z(x,y,0)*normal_vector(1)+diffusive_coefficient_21z(x,y,0)*normal_vector(2))*triangular_local_basis(x,y,basis_type,1,0)...
       +(diffusive_coefficient_21z(x,y,0)*normal_vector(1)+diffusive_coefficient_22z(x,y,0)*normal_vector(2))*triangular_local_basis(x,y,basis_type,0,1))'...
  *triangular_local_basis(x,y,basis_type,0,0)...
 +eipsilon*triangular_local_basis(x,y,basis_type,0,0)'...
 *((diffusive_coefficient_11z(x,y,0)*normal_vector(1)+diffusive_coefficient_21z(x,y,0)*normal_vector(2))*triangular_local_basis(x,y,basis_type,1,0)...
       +(diffusive_coefficient_21z(x,y,0)*normal_vector(1)+diffusive_coefficient_22z(x,y,0)*normal_vector(2))*triangular_local_basis(x,y,basis_type,0,1))...
 +1/e^beta*sigma*penalty_diffusive_coefficient_z(x,y,0)*triangular_local_basis(x,y,basis_type,0,0)'...
                  *triangular_local_basis(x,y,basis_type,0,0);