function r=integrand_3_on_edges_e(x,y,t,penalty,edge_information,basis_type,eipsilon,e,beta)

normal_vector=edge_information(1:2);

r=eipsilon*function_boundary_time_derivate(x,y,t)...
          *((diffusive_coefficient_11e(x,y,0)*normal_vector(1)+diffusive_coefficient_21e(x,y,0)*normal_vector(2))*triangular_local_basis(x,y,basis_type,1,0)...
       +(diffusive_coefficient_21e(x,y,0)*normal_vector(1)+diffusive_coefficient_22e(x,y,0)*normal_vector(2))*triangular_local_basis(x,y,basis_type,0,1))'...
 +1/e^beta*function_boundary_time_derivate(x,y,t)...
          *penalty*penalty_diffusive_coefficient_e(x,y,0)*triangular_local_basis(x,y,basis_type,0,0)';